//go:build !ignore_autogenerated

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

func (in *SecretUsage) DeepCopyInto(out *SecretUsage) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

func (in *SecretUsage) DeepCopy() *SecretUsage {
	if in == nil {
		return nil
	}
	out := new(SecretUsage)
	in.DeepCopyInto(out)
	return out
}

func (in *SecretUsage) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *SecretUsageList) DeepCopyInto(out *SecretUsageList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]SecretUsage, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *SecretUsageList) DeepCopy() *SecretUsageList {
	if in == nil {
		return nil
	}
	out := new(SecretUsageList)
	in.DeepCopyInto(out)
	return out
}

func (in *SecretUsageList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *SecretUsageReference) DeepCopyInto(out *SecretUsageReference) {
	*out = *in
	if in.Optional != nil {
		in, out := &in.Optional, &out.Optional
		*out = new(bool)
		**out = **in
	}
}

func (in *SecretUsageReference) DeepCopy() *SecretUsageReference {
	if in == nil {
		return nil
	}
	out := new(SecretUsageReference)
	in.DeepCopyInto(out)
	return out
}

func (in *SecretUsageSpec) DeepCopyInto(out *SecretUsageSpec) {
	*out = *in
}

func (in *SecretUsageSpec) DeepCopy() *SecretUsageSpec {
	if in == nil {
		return nil
	}
	out := new(SecretUsageSpec)
	in.DeepCopyInto(out)
	return out
}

func (in *SecretUsageStatus) DeepCopyInto(out *SecretUsageStatus) {
	*out = *in
	if in.Usages != nil {
		in, out := &in.Usages, &out.Usages
		*out = make([]SecretUsageReference, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *SecretUsageStatus) DeepCopy() *SecretUsageStatus {
	if in == nil {
		return nil
	}
	out := new(SecretUsageStatus)
	in.DeepCopyInto(out)
	return out
}
